name: desktop-adb-file-browser
version: 0.1.0
summary: ADB File Browser for Android devices
description: Sidequest file browser sux

confinement: strict
base: core18
grade: stable

slots:
  dbus-desktop-adb-file-browser: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.github.fernthedev.desktop-adb-file-browser # adjust accordingly to your app name and
    
apps:
  desktop-adb-file-browser:
    command: desktop_adb_file_browser
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-desktop-adb-file-browser
parts:
  desktop-adb-file-browser:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
