name: Rust CI

on:
  push:
  #  branches: [ master ]
  pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.runner}}

    strategy:
      matrix:
        target: [macos-x64, windows-x64, linux-x64]
        include:
        # - target: macos-arm64
        #   os: macos
        #   arch: arm64
        #   runner: macOS-latest

        - target: macos-x64
          os: macos
          arch: x64
          runner: macOS-latest

        - target: windows-x64
          os: windows
          arch: x64
          runner: windows-latest

        - target: linux-x64
          os: linux
          arch: x64
          runner: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Linux deps
      if: contains(matrix.runner, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
        architecture: ${{matrix.arch}} # optional, x64 or arm64
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build ${{matrix.os}}
      
    - name: Create MSIX installer
      if: contains(matrix.runner, 'windows')
      run: flutter pub run msix:create
      
      # TODO: Linux and Mac artifacts

    - name: Upload Windows artifacts (archive)
      if: contains(matrix.runner, 'windows')
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: ./build/windows/runner/Release/*
        if-no-files-found: error

    - name: Upload Windows MSIX installer
      if: contains(matrix.runner, 'windows')
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }} msix installer
        path: |
          ./build/windows/runner/Release/*.msix
        if-no-files-found: error